Make bincode_derive 0 dependencies
bincode-org/bincode pull request #409
Opened 2021-10-07 13:39 UTC by VictorKoenders

This PR removes `syn`, `proc_macro2` and `quote` from `bincode_derive`.

We still have to keep `proc_macro2` as a dev dependency as it is otherwise impossible to test the parser. This is automatically used instead of `proc_macro` when running tests.

The change is roughly split into 2 parts:

# Parsing

Most of parsing is done in the `derive/src/parse/` folder. This will generate the following types:
- `Visibility`, not being used currently
- `DataType` either `Struct` or `Enum`, with the name of the data type being parsed
- `Generics` the generics part of the type, e.g. `struct Foo<'a>`
- `GenericConstraints` the "where" part of the type

# Generate

Generating the code implementation is done in either `derive/src/derive_enum.rs` and `derive/src/derive_struct.rs`.

This is supported by the structs in `derive/src/generate`. The most notable points of this module are:
- `StreamBuilder` is a thin but friendly wrapper around `TokenStream`
- `Generator` is the base type of the code generator. This has helper methods to generate implementations:
  - `ImplFor` is a helper struct for a single `impl A for B` construction. In this functions can be defined:
    - `GenerateFnBody` is a helper struct for a single function in the above `impl`. This is created with a callback to `FnBuilder` which helps set some properties. `GenerateFnBody` has a `stream()` function which returns ` StreamBuilder` for the function.

The code is tested against the current cases in `tests/derive.rs`, **however** we'll need a lot more test cases before this PR can be merged.

For testing purposes, all generated code is outputted to the current `target` folder, under file name `<struct/enum name>_Encodeable.rs` and `<struct/enum name>_Decodeable.rs`. This can help with debugging.

2021-10-07 14:13 UTC, ghost requested changes

2021-10-07 14:13 UTC, ghost commented on Cargo.toml
> +resolver = "2"
Did cargo do this automatically?

2021-10-07 14:13 UTC, ghost commented on derive/src/parse/body.rs
> +        // An enum variant is a struct variant if it has no fields with a name
This comment should say `tuple variant`

2021-10-07 14:13 UTC, ghost commented on derive/src/derive_enum.rs
> +                    let delimiter = if variant.is_struct_variant() {
I think it would make more sense to have a `variant.kind()` method that returns an enum of `Struct, Tuple, Unit` instead of having separate `is` methods.

2021-10-07 14:13 UTC, ghost commented on derive/src/error.rs
> +    fn eq(&self, other: &Error) -> bool {
Why are the `Span`s not compared for equality?

2021-10-07 14:13 UTC, ghost commented on derive/src/derive_struct.rs
> +            fn_body.push_parsed(format!(
It would be useful to somehow add the span of the original field to this part of the token stream. That way if the field doesn't implement `Encodable` the compiler error will produce lines at the correct place. This probably applies other places, but I'll just comment it here for now.

2021-10-07 14:13 UTC, ghost commented on derive/src/generate/mod.rs
> +        builder: impl FnOnce(FnBuilder) -> FnBuilder,
I'm not a huge fan of the closure API. Would be possible to change this to return a builder with a `build()` method instead?

2021-10-07 14:13 UTC, ghost commented on derive/src/generate/mod.rs
> +    // pub fn with_lifetime(
Remove commented out code please

2021-10-07 14:13 UTC, ghost commented on derive/src/parse/body.rs
> +        assert!(
Could this be turned into a debug_assert or an Error variant instead?

2021-10-07 14:13 UTC, ghost commented on derive/src/parse/visibility.rs
> +                            if super::ident_eq(&ident, "crate") {
other visibilities than `crate` are allowed

2021-10-08 07:24 UTC, VictorKoenders commented on Cargo.toml
> +resolver = "2"
No I added this manually. Resolver 2 is standard in the 2021 edition, and I think this won't actually do anything if it's not in the binary (plus we have almost no dependencies). I'll remove it

2021-10-08 08:18 UTC, VictorKoenders commented on derive/src/parse/body.rs
> +        // An enum variant is a struct variant if it has no fields with a name
Reworked the struct/enum variant fields

2021-10-08 08:18 UTC, VictorKoenders commented on derive/src/derive_enum.rs
> +                    let delimiter = if variant.is_struct_variant() {
Done!

2021-10-08 08:19 UTC, VictorKoenders commented on derive/src/error.rs
> +    fn eq(&self, other: &Error) -> bool {
`PartialEq` was only implemented for `Error` for the tests so that `partial_eq!()` could be used. I've removed the `PartialEq` implementation and used all the `.is_` methods and `.unwrap()`

2021-10-08 08:21 UTC, VictorKoenders commented on derive/src/parse/body.rs
> +        assert!(
The `assert` should only panic if the fields of the structs are improperly parsed. I'm assuming the parser is properly tested at this point and we don't need this assert, so I'll remove it.

2021-10-08 08:32 UTC, VictorKoenders commented on derive/src/derive_struct.rs
> +            fn_body.push_parsed(format!(
Because this is formatted into a string and then passed to `.push_parsed`, we're dependent on the `Span` value of the implementation of the `FromStr` in either `proc_macro` (for users) or `proc_macro2` (during tests).

I'll add a `Span` location to `IdentOrIndex::Index` but I doubt it'll ever come up

2021-10-08 08:35 UTC, VictorKoenders commented on derive/src/parse/visibility.rs
> +                            if super::ident_eq(&ident, "crate") {
Because we're not actually using the value of `Visibility` I've changed it to simply consume everything the parenthesis. Visibility is now either `::Default` for no visibility and `::Pub` for `pub` and `pub(anything)`

2021-10-08 08:51 UTC, VictorKoenders commented on derive/src/generate/mod.rs
> +        builder: impl FnOnce(FnBuilder) -> FnBuilder,
I have flipped it around. Configuring the function definition is now a builder pattern, and the body is inside of a closure. The body is a nested group so it makes sense to be a similar closure like `StreamBuilder::group`.

2021-10-12 08:46 UTC, ghost commented on derive/src/error.rs
> +            // Error::UnionNotSupported => None,
Remove this

2021-10-12 08:46 UTC, ghost commented on src/de/mod.rs
> +    // }: for<'de> BorrowDecodable<'de> {
why is this here?

2021-10-12 10:44 UTC, ZoeyR commented
Looks like this parser can't handle field attributes (i.e. `#[serde(skip)]`). It shouldn't be too bad to add them because as far as I can tell they can all be ignored.

2021-10-12 13:07 UTC, VictorKoenders commented on derive/src/error.rs
> +            // Error::UnionNotSupported => None,
Removed

2021-10-12 13:07 UTC, VictorKoenders commented on src/de/mod.rs
> +    // }: for<'de> BorrowDecodable<'de> {
Leftover from when I was trying to make the derive crate work, reverted this change

2021-10-12 13:16 UTC, ghost commented on src/de/mod.rs
> -pub trait Decodable: for<'de> BorrowDecodable<'de> {
I really hate to nitpick but could you remove the `Sized`? Its implied by BorrowDecodable

2021-10-12 13:19 UTC, ghost approved these changes

2021-10-12 13:19 UTC, VictorKoenders commented on src/de/mod.rs
> -pub trait Decodable: for<'de> BorrowDecodable<'de> {
Done

2021-10-12 13:53 UTC, merged