Put clarifying language in migration guide regarding the serde:: and non-serde:: paths
bincode-org/bincode pull request #715
Opened 2024-05-28 01:08 UTC by mcclure

This past week I ported a crate from bincode1 to bincode2. I had some difficulty because I took the "migrate serde to bincode-derive" path, which was not appropriate for my application. I was following the migration guide, but I misread it.

I would like to recommend some minor language tweaks to make the migration guide more resistant to misinterpretation. Proposed language is attached, but I don't care if you use my specific language. I do suggest you make *some* form of the following changes:

* Make it clearer that the "Migrating with `serde`" and "Migrating to `bincode-derive`" sections describe *exclusive* options.
* Describe why someone might want to migrate with serde.

This would have helped me do my porting correctly the first time.

2024-05-28 07:55 UTC, VictorKoenders requested changes

2024-05-28 07:55 UTC, VictorKoenders commented on docs/migration_guide.md
> +If so, make sure to include bincode 2 with the `serde` feature enabled.
Might be useful to also mention that people should use the `bincode::serde::*` functions instead of the `bincode::*` functions

2024-08-02 21:24 UTC, mcclure commented
Nothing has changed, so this problem is still real. I still think this patch should be merged.

2024-08-03 10:47 UTC, VictorKoenders commented
Please fix the change I've requested and we can get this merged

2024-08-03 20:18 UTC, mcclure commented
Sorry, I misunderstood your comment before. Is that better?

2024-08-07 08:00 UTC, merged

2024-08-07 08:00 UTC, VictorKoenders commented
Thanks!